### PR TITLE
Pull Request

### PR DESCRIPTION
**Pull request by ashar02**
I have made few changes in code. Please review it and take action accordingly. I shall try to contribute on this code on daily basis onwards.

### CODE REVIEW

**Comment by zevarito** [comment]
@ashar02 thanks for you contributions.

Could you revisit a few small things before merge?

1) I understand the idea of having the possibility to send custom attributes at the moment of publishing a stream, but I'd prefer to have 2 methods instead.

So, we have this...
```objc
// Method 1
- (void)publish:(ECStream *)stream withOptions:(NSDictionary *)options;
```
We should add something like this...
```objc
// Method 2
- (void)publish:(ECStream *)stream withOptions:(NSDictionary *)options customOptions:(NSDictionary)customOptions;
```
Where first method should be a forward call to the second one with `customOptions` set to `nil`.

Also `customAttributes` as key is very own to your own implementation so I'd say `customOptions` should be merged at the same level as `options` by default. If you want to namespace it you should do it in the `customOptions` itself and pass an object like:

```objc
@{
  "customKeyCustomOptions": @{ /* ... */ };
}
```
Please document new method in interface appropriately.
It uses [AppleDoc](https://github.com/tomaz/appledoc) in case you need reference.

2) Please follow code guidelines as it is already in code like...

Instead of
```objc
for(int i ...
if(something ...
```
do
```objc
for (int i ...
if (something ...
```
Notice `space` after `(`.

3) Indentation of this file/line doesn't look very good:

https://github.com/ashar02/ErizoClientIOS/blob/7818b8ec9578d1868f0ae870a52bd0811241ad00/ECIExampleLicode/ECIExampleLicode/LicodeServer.m#L37

Thanks again for your work.

**Comment by ashar02** [comment]
I have done all the changes. Let me know if you need any things else?

**Comment by ashar02** [comment]
hi,

Yes, it will produce the dictionary like this:

@{
    @"data": @"true|false",
    @"video": @"true|false",
    @"audio": @"true|false",
    @"attributes": @{  /*... */ }
}

Actually I followed this link: http://lynckia.com/licode/client-api.html#initStream
Its actually a JS client code. Copying few lines below for reference:

var stream = Erizo.Stream({audio:true, video:false, data: true, attributes: {name:'myStream'}});

audio, video and data variables has to be set to true if you want to publish them in the room. While attributes variable can store additional information related to the stream. This information will be shared between clients in the room.

getAttributes()	Gets the attributes variable stored when you created the stream.
setAttributes()	It sets new attributes to the local stream that are spread to the room.

So after reading this help. I feel that we should also make the key 'attributes' same and let the users of this code to just set the custom values inside it.

What you say regarding this?

**Comment by zevarito** [comment]
Yup if that is the standard that is the way to go. I'll finish the review
by Monday and then merge. Thanks Ashar.

On Saturday, September 19, 2015, ashar_clary <notifications@github.com>
wrote:

> hi,
>
> Yes, it will produce the dictionary like this:
>
> @{
> @"data": @"true|false",
> @"video": @"true|false",
> @"audio": @"true|false",
> @"attributes": @{ /*... */ }
> }
>
> Actually I followed this link:
> http://lynckia.com/licode/client-api.html#initStream
> Its actually a JS client code. Copying few lines below for reference:
>
> var stream = Erizo.Stream({audio:true, video:false, data: true,
> attributes: {name:'myStream'}});
>
> audio, video and data variables has to be set to true if you want to
> publish them in the room. While attributes variable can store additional
> information related to the stream. This information will be shared between
> clients in the room.
>
> getAttributes() Gets the attributes variable stored when you created the
> stream.
> setAttributes() It sets new attributes to the local stream that are spread
> to the room.
>
> So after reading this help. I feel that we should also make the key
> 'attributes' same and let the users of this code to just set the custom
> values inside it.
>
> What you say regarding this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/pull/12#issuecomment-141691541>
> .
>


-- 
Sent from Gmail Mobile

**Comment by ashar02** [comment]
No problem

**Comment by zevarito** [comment]
Hi @ashar02,

So, I was giving a deeper look into this and it doesn't convince me. Here is the thing...

The link you've pasted: http://lynckia.com/licode/client-api.html#initStream is at Stream level, equivalent for us is ECStream, I agree could be nice to support custom attributes there.

What doesn't look ok to me is to use `publish` method to send them. Licode JS client itself is not using it: [0], what it does is to update them in a callback after publishing: [1], but it uses setAttributes/getAttributes API, which essentially send another event type[3], not publish.

Could be great if you could leave d1dde12, 7056c7c, 7818b8e, bb175ea in one branch so I can merge them without cherry-picking bb175ea because 4ac1b21(custom attribute support) is in the middle, and if I cherry-pick that it will give you conflicts when you merge back.
Also `attributes` looks like deserves a single branch and PR when it gets done.

Thoughts?

[0] https://github.com/ging/licode/blob/6a3892e3bda7b4ec06f950a226a9458e74517077/erizo_controller/erizoClient/src/Room.js#L335

[1] https://github.com/ging/licode/blob/6a3892e3bda7b4ec06f950a226a9458e74517077/erizo_controller/erizoClient/src/Room.js#L378

[2] http://lynckia.com/licode/client-api.html#setAttributes

[3] https://github.com/ging/licode/blob/6a3892e3bda7b4ec06f950a226a9458e74517077/erizo_controller/erizoClient/src/Room.js#L95

**Comment by ashar02** [comment]
Hi,

Good to know that you look things in deeper. Here are my thoughts:

Yes, JS code implemented attributes in Stream class which is equivalent to ECStream. In JS code, options are used for bandwidth control of audio or video. But here in our code we use options to control data stream (on/off). That is why I used attributes as separate argument to publish method.

Also publish method sends the attributes initially as well as in callback. See the JS code:
https://github.com/ging/licode/blob/6a3892e3bda7b4ec06f950a226a9458e74517077/erizo_controller/erizoClient/src/Room.js#L367 

And it uses stream object to get the video, audio, data, attributes etc. to send it.

So what I can do is to make a getter and  setter in ECStream class. Remove the customOptions argument from the Room publish method. And inside room publish method implementation, I can get attributes from the stream object and set it on opts dictionary to send. And similar thing can be done in for data too.

What you say?

**Comment by zevarito** [comment]
@ashar02 yes, I second that implementation, so just to ensure we are in the same page.

Let's go with this:
* Attributes are get/set in ECStream.
* Once a Stream is published, attributes are sent as soon as the stream gets successfully published.

And later we add this:
* Each time Attributes are modified for a published stream they should be sent to the server.

**Comment by ashar02** [comment]
Agreed !!

I have committed the code. Please review and let me know if any change is required.

**Comment by zevarito** [comment]
@ashar02 merged, thanks.

**Pull request merged**
